### ISSUE TITLE
Compatibility with React 18

### ISSUE THREAD

**Issue by BaldFabi** [renatomoor/storybook-tailwind-dark-mode#10]
I'm currently working on a project using React 18 and Storybook 6.5.
To use the plugin I had to force the installation. Any chance to add the official compatibility for React 18?

**Comment by anhthien-bic** [comment]
same issue

**Comment by arunavo4** [comment]
same problem

**Comment by sutter** [comment]
same issue

**Comment by huaiyukhaw** [comment]
same issue

**Comment by renatomoor** [comment]
Fixed on v1.0.13

**Comment by DeadIine** [comment]
I'm still having this issue. 

I looked at the PR and your package.json. Only `react-dom` was updated.

What about `react` itself?  I opened a PR for this (https://github.com/renatomoor/storybook-tailwind-dark-mode/pull/11)

**Comment by YiDaoJ** [comment]
same issue

**Comment by LeNei** [comment]
Same here
